CREATE TABLE SENSORS(
  SEN_ID VARCHAR[15] PRIMARY KEY NOT NULL AUTO_INCREMENT,
  SEN_LAT FLOAT,
  SEN_LON FLOAT,
  SEN_IP VARCHAR[15]
)

CREATE TABLE DATA(
  DT_ENTRY INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DT_SENSOR_ID VARCHAR[15] NOT NULL,
  DT_TEMP FLOAT,
  DT_HUM FLOAT,
  DT_DATE DATE NOT NULL
)
