CREATE TABLE SENSORS(
  SEN_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  SEN_LAT FLOAT,
  SEN_LON FLOAT,
  SEN_IP VARCHAR[15]
)

CREATE TABLE DATA(
  DT_ENTRY INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DT_SENSOR_ID INT NOT NULL,
  DT_TEMP FLOAT,
  DT_HUM FLOAT,
  DT_DATE DATE NOT NULL,
  FOREIGN KEY (DT_SENSOR_ID) REFERENCES SENSORS(SEN_ID)
)
